[package]
name = "tts_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
rodio = "0.15"
dotenv = "0.15"
clipboard = "0.5.0"


