name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build project
        run: cargo build --release

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            if [ ! -d "/home/ec2-user/tts-reader-rust" ]; then
              git clone https://github.com/AJStolp/tts-reader-rust.git /home/ec2-user/tts-reader-rust
            fi
            cd /home/ec2-user/tts-reader-rust
            git pull origin main
            cargo build --release
            sudo systemctl restart tts-app
