name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build project
        run: cargo build --release

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 3.86.199.1
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/tts-reader-rust || exit
            git pull origin main
            cargo build --release
            sudo systemctl restart tts-app
