name: Deploy to EC2

on:
  push:
    branches:
      - main # Trigger this workflow when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner for this job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Rust toolchain
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Step 3: Build the project locally for validation (optional)
      - name: Build project (for validation)
        run: cargo build --release

      # Step 4: SSH into EC2 and deploy the project
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # Public IP of your EC2 instance
          username: ${{ secrets.EC2_USER }} # SSH username (e.g., ec2-user)
          key: ${{ secrets.EC2_PRIVATE_KEY }} # Your private key for SSH access
          script: |
            # Change directory to your project folder or clone it if not present
            if [ ! -d "/home/ec2-user/tts-reader-rust" ]; then
              git clone https://github.com/AJStolp/tts-reader-rust.git /home/ec2-user/tts-reader-rust
            fi

            # Navigate to project directory
            cd /home/ec2-user/tts-reader-rust

            # Pull the latest code
            git pull origin main

            # Build the project using Cargo
            cargo build --release

            # Restart the service
            sudo systemctl restart tts-app
